[build]
  command = "cd frontend && npm install --legacy-peer-deps && chmod +x node_modules/.bin/react-scripts && npm run build"
  publish = "frontend/build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18" # Try a version compatible with your react-scripts
  NPM_FLAGS = "--legacy-peer-deps"
